name: Trivy Scan

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.61.0/trivy_0.61.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.61.0_Linux-64bit.deb

      - name: Get image information
        id: get-image-info
        run: |
          IMAGE_NAME=$(jq -r '.name' package.json)
          IMAGE_VERSION=$(jq -r '.version' package.json)
          echo "IMAGE=quay.io/okdp/$IMAGE_NAME:$IMAGE_VERSION" >> $GITHUB_ENV

      - name: Run Trivy scan
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL $IMAGE
